version: "3"
services:
  app:
    build: .
    volumes:
      - ${PWD}:/app
    command: ['npm', 'start']
    ports:
      - 3030:3030
    depends_on:
      - mongo
  mongo:
    image: mongo
    expose:
    - 27017